These are code snippets that I use to try new things before putting them into a tutorial notebook.

1. Diamond Square Lattice

In [ ]:
from crystalbuilder import *
import numpy as np
import crystalbuilder.geometry as geo
import matplotlib.pyplot as plt
import numpy as np
import vedo

diam = bilbao.SpaceGroup(227)

points = diam.calculate_points([(1/8,1/8,1/8)])



In [2]:
newpoints = np.unique((points), axis=0)
print(newpoints)
print(newpoints.shape)

a1 = [1, 0, 0]
a2 = [0, 1 ,0]
a3 = [0, 0, 1]

a_mag = 1

geo_lattice = lattice.Lattice(a1, a2, a3, magnitude = [a_mag, a_mag, a_mag])

radius = .01

conn = geo.NearestNeighbors(newpoints, radius=radius, neighborhood_range=.45)
a1_reps = 5
a2_reps = 5
a3_reps = 5
crystal = geo_lattice.tile_geogeometry(conn.structure_list, a1_reps, a2_reps, a3_reps )


[[-0.125 -0.125 -0.125]
 [-0.125  0.375  0.375]
 [-0.125  0.875  0.875]
 [ 0.125  0.125  0.125]
 [ 0.125  0.625  0.625]
 [ 0.375 -0.125  0.375]
 [ 0.375  0.375 -0.125]
 [ 0.375  0.375  0.875]
 [ 0.375  0.875  0.375]
 [ 0.625  0.125  0.625]
 [ 0.625  0.625  0.125]
 [ 0.875 -0.125  0.875]
 [ 0.875  0.375  0.375]
 [ 0.875  0.875 -0.125]]
(14, 3)


In [3]:
plot = viewer.visualize(crystal)
plot.show().close()