In [24]:
from sklearn.cluster import DBSCAN

In [25]:
import numpy as np

In [26]:
X = np.array([[1, 2], [2, 2], [2, 3], [8, 7], [8, 8], [25, 80]])

In [27]:
clustering = DBSCAN(eps=3, min_samples=2).fit(X)

In [28]:
clustering.labels_

array([ 0,  0,  0,  1,  1, -1], dtype=int64)

In [30]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=len(set(clustering.labels_)))

In [31]:
kmeans.fit_predict(X)

C:\Users\adina\anaconda3\envs\m\lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
C:\Users\adina\anaconda3\envs\m\lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


array([0, 0, 0, 2, 2, 1])

In [35]:
y_pred = np.array([8, 80])
y_pred = kmeans.predict(X)

In [38]:
y_pred = np.array([8, 80])
y_pred = kmeans.predict([y_pred])

In [39]:
y_pred

array([1])